### ISSUE TITLE
Hide/show password

### ISSUE THREAD

**Issue by mansogf** [Computer-Progress/computerprogress.com#47]
**Description**
In the "Sign In" component (Figure 1), the hide/show functionally (the eye) was not implemented as it is in other components as shown in Figure 2.

**_Figure 1:_**
<img width="601" alt="Captura de Tela 2021-08-30 às 19 23 30" src="https://user-images.githubusercontent.com/37154573/131883407-d8ef8cbe-c7a9-4a6e-bbea-792d6b858d2c.png">

**_Figure 2:_**
<img width="1223" alt="Captura de Tela 2021-08-21 às 15 39 40" src="https://user-images.githubusercontent.com/37154573/131884008-c9de4b2d-1b54-4c63-9d6c-4de84a548fb9.png">

**Tasks**

- [ ] Implement the hide/show functionally to all components that involve a password.

**Comment by J-Matheus** [comment]
I'm working in this.

**Comment by J-Matheus** [comment]
PR: https://github.com/Computer-Progress/computerprogress.com/pull/54
