### ISSUE TITLE
Footer is not at the bottom

### ISSUE THREAD

**Issue by irwinschmitt** [Computer-Progress/computerprogress.com#51]
**Describe the bug**
When content doesn't fully fill the screen, the footer doesn't stay at the bottom of the page

**To Reproduce**
1. Go to any page.
2. Zoom out

**Expected behavior**
The footer should always stay at the bottom of the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/44441530/131928272-07ac3743-d36e-4ebf-a337-0cc79b042d56.png)

**Desktop (please complete the following information):**
- OS: Windows
- Firefox
- Version 91.0.2 (64 bits)

**Additional context**
Check the Material-Ui configuration.

**Comment by fellipe-araujo** [comment]
I will solve this issue.

**Comment by fellipe-araujo** [comment]
I finished this issue. PR #53

**Comment by fellipe-araujo** [comment]
I found some bugs in production mode, i will fix.

**Comment by fellipe-araujo** [comment]
Bugs fixed!
